import type { Metadata } from "next";
import { Noto_Sans_KR, Noto_Sans } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/Footer";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-Sans-kr',
});

const notoSans = Noto_Sans({
  subsets: ["latin"],
  display: 'swap',
  variable: '--font-Sans-en',
});

export const metadata: Metadata = {
  title: "Power Tools",
  description: "Generated by MG-AI",
  icons: {
    icon: "/favicon.ico",
  }
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={`${notoSans.variable} ${notoSansKr.variable}`}>
        <div className="layout__box">
          <Header />
          <div className="contents">{children}</div>
          <Footer />
        </div>
      </body>
    </html>
  );
}
