import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  display: 'swap',
});

export const metadata: Metadata = {
  title: "Power Tools",
  description: "Generated by MG-AI",
};

export default function RootLayout({ children,}: Readonly<{ children: React.ReactNode; }>) {
  return (
    <html lang="en">
      <body className={notoSansKr.className}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
